name: Codestyle flake8

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-return flake8-isort flake8-bugbear flake8-comprehensions flake8-pie flake8-print flake8-quotes flake8-simplify flake8-variables-names
        pip install -r requirements.txt 

    - name: Test with flake8
      run: |
        python -m flake8
  
