name: develop

on:
  pull_request:
    branches: [cicd]
  push:
    branches: [cicd]

env:
  REGISTRY: cr.selcloud.ru
  IMAGE_NAME: tg_bot_dev

# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.10'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip3 install poetry
#         curl -sSL 'https://install.python-poetry.org' | python3 -
#         poetry config virtualenvs.create false
#         poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi
#         poetry add flake8-bugbear
#         poetry add flake8-return
#         poetry add flake8-comprehensions
#         poetry add flake8-pie
#         poetry add flake8-print
#         poetry add flake8-quotes
#         poetry add flake8-simplify
#         poetry add flake8-variables-names
#         poetry add pep8-naming
#         poetry add flake8-docstrings
#         pre-commit install
#     - name: Test with flake8 and pre-commit
#       run: |
#         python -m flake8 .
#         pre-commit run --all-files

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SELECTEL_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.SELECTEL_CONTAINER_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ github.workflow }}-${{ github.run_number }}
