name: develop

on:
  pull_request:
    branches: [cicd]
  push:
    branches: [cicd]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install poetry
        curl -sSL 'https://install.python-poetry.org' | python3 -
        poetry config virtualenvs.create false
        poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi
        poetry add flake8-bugbear
        poetry add flake8-return
        poetry add flake8-comprehensions
        poetry add flake8-pie
        poetry add flake8-print
        poetry add flake8-quotes
        poetry add flake8-simplify
        poetry add flake8-variables-names
        poetry add pep8-naming
        poetry add flake8-docstrings
        pre-commit install
    - name: Test with flake8 and pre-commit
      run: |
        python -m flake8 .
        pre-commit run --all-files

  build_push_to_CR:
    name: Building tg_bot image and pushing it to CR
    runs-on: ubuntu-latest
    needs: tests
    steps:

    - name: Login to docker in Selectel CR
      uses: docker/login-action@v2
      with:
        registry: cr.selcloud.ru
        username: ${{ secrets.SELECTEL_CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.SELECTEL_CONTAINER_REGISTRY_PASSWORD_PASS }}

    - name: Build and tag docker image
      run: |
        docker build -t tg_bot_dev .
        docker tag tg_bot_dev cr.selcloud.ru/registry/tg_bot_dev:${{ github.workflow }}-${{ github.run_number }}

    - name: push docker image
      run: |
        docker push cr.selcloud.ru/registry/tg_bot_dev:${{ github.workflow }}-${{ github.run_number }}
        docker logout cr.selcloud.ru
 
  deploy_pool_create_from_CR:
    runs-on: ubuntu-latest
    needs: build_push_to_CR
    steps:

    - name: Remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SELECTEL_SERVER_HOST_IP }}
        username: ${{ secrets.SELECTEL_SERVER_HOST_USER }}
        key: ${{ secrets.SELECTEL_SERVER_SSH_PUB_KEY }}
        passphrase: ${{ secrets.SELECTEL_SERVER_SSH_PUB_KEY_PASSWORD }}
        script: |
          docker login -u ${{ secrets.SELECTEL_CONTAINER_REGISTRY_USER }} 
          -p ${{ secrets.SELECTEL_CONTAINER_REGISTRY_PASSWORD }}
          docker pull cr.selcloud.ru/registry/tg_bot_dev:${{ github.workflow }}-${{ github.run_number }}
          docker logout cr.selcloud.ru
          docker container rm tg_bot_dev_container --force
          docker container create -it --name tg_bot_dev_container cr.selcloud.ru/registry/tg_bot_dev:${{ github.workflow }}-${{ github.run_number }}
          docker container start tg_bot_dev_container

    - name: Create env file and start project
      run: |
        docker exec -it tg_bot_dev_container bash
        echo touch .env
        echo BOT_TOKEN="${{ secrets.PH_TOKEN_BOT_TEST }}" >> .env
        echo URL_DONATION=${{ secrets.URL_DONATION }} >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY_BOT }} >> .env
        echo python -m bin.run_bot
        echo exit
